development:
  adapter: postgresql
  encoding: unicode
  database: snips_development
  pool: 5
  username: postgres
  password: password
  min_messages: WARNING
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: snips_test<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 5
  username: postgres
  password: password
  min_messages: WARNING
  host: localhost
